#GPIO # on ESP32-D1 mini
####### Mic INMP441
# 3V3 # 3.3v
# GND # ground
#  21 # WS
#  17 # SCK
#  23 # SD
####### Speaker (DAC/Amplifier) MAX98357a
# VCC # 5v
# GND # ground
#  21 # LRC (or LRCLK)
#  17 # BCLK
#  16 # DIN
####### Button (any)
# GND # ground
#  22 # button
#
# REMEMBER TO REPLACE THE API KEY WITH YOUR OWN - and change the name & friendly name of the device ;)
esphome:
  name: esphome-web-e7c448
  friendly_name: ESP32D1-Notifier
  min_version: 2023.10.0
  on_boot:
    - priority: -100
      then:
        - wait_until: api.connected
        - delay: 1s
        - if:
            condition:
              switch.is_on: use_wake_word
            then:
              - voice_assistant.start_continuous:

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "QOv11vJiZQeYwycW1VazP5xBmGuRKT1AdhPxZt86bnI="

ota:


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

i2s_audio:
    i2s_lrclk_pin: GPIO21 # (LRC)
    i2s_bclk_pin: GPIO17 # (BCLK)

microphone:
  - platform: i2s_audio
    id: echo_microphone
    i2s_din_pin: GPIO23  # DIN, SDIN, SD, SDATA, ADCDATA
    adc_type: external
    pdm: false
    bits_per_sample: 32bit


voice_assistant:
  id: va
  microphone: echo_microphone
  noise_suppression_level: 2
  auto_gain: 31dBFS
  volume_multiplier: 2.0
  use_wake_word: True 
  on_listening:
    - light.turn_on: response_light
  on_end:
    - light.turn_off: response_light

output:
  - platform: gpio
    pin: GPIO2  #onboard led
    id: light_output

light:
  - platform: binary
    name: "Wake Word"
    id: response_light
    output: light_output

switch:
  - platform: template
    name: Use wake word
    id: use_wake_word
    optimistic: true
    restore_mode: RESTORE_DEFAULT_ON
    entity_category: config
    on_turn_on:
      - lambda: id(va).set_use_wake_word(true);
      - if:
          condition:
            not:
              - voice_assistant.is_running
          then:
            - voice_assistant.start_continuous

    on_turn_off:
      - voice_assistant.stop
      - lambda: id(va).set_use_wake_word(false);
